### ISSUE TITLE
For anyone interested in working on Savate Serif

### ISSUE THREAD

**Issue by johnvetter** [GD399-OSD/Savate-Serif#1]
Problems I have found so far but have not fixed:
–The cap 'X' is too tall
–The space character needs to be larger
–The cap 'A' is too heavy
–Lots of spacing to be fixed

Further questions:
–How to tackle the lower case
–The serifs are making everything heavier, should we try to balance the weight, or let the serif-face just be naturally heavier than the sans?
–Should lowercase 'tail' serifs reflect the 'a' and 'l'? Or should the serifs be blocky like the caps?
–Should the cap 'Q' be made more serif-like? If so, how?
–No rush on this, but I haven't had a chance to check out how to kern in FontForge? Has anyone figured that out? (This typeface could definitely use it)

PS:
Here's my type design resource are.na board for sites that help with designing type. (some tools, some instructional sites). Please add more type design sites if you know them! https://www.are.na/john-vetter/type-design-resources-1519400508

**Comment by bjornmeansbear** [comment]
AWESOME! we have a concrete project in the works! we should see if the Savate peeps/Velvetyne are interested in this as it progresses?

If that X is really busted in Savate we should fix that and pull request it back to them!
