### ISSUE TITLE
Is this the most up to date?

### ISSUE THREAD

**Issue by bjornmeansbear** [GD399-OSD/Savate-Serif#2]
@johnvetter I was going to send this to a few people — have you updated the repo with your most up to date version?

**Comment by johnvetter** [comment]
Hey!

Sorry I was midway writing you back and got distracted and totally forgot to finish. But yes! The most up to date one is up, but I do plan on finishing up accents and such! Maybe doing some kerning as well

**Comment by bjornmeansbear** [comment]
Awesome. Just checking. Yes! keep working on it!
Also, if you fancied yourself free of time — you should still fix the X in regular savate and submit a pull request to them!
